config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index'

  resources :patients
  resources :doctors
  resources :appointments, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates_presence_of :first_name, :last_name

  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates_presence_of :first_name, :last_name

  has_many :doctors
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @doctors = Doctor.all.map { |d| [d.first_name, d.last_name, d.id] }
    @patients= Patient.all.map { |p| [p.first_name, p.last_name, p.id] }
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash[:notice] = 'Appointment Added'
      redirect_to :back
    else
      render :new
    end
  end

  def destroy
    appointment = Appointment.find(params[:id])
    appointment.destroy
    flash[:success] = 'Appointment Removed'
    redirect_to doctor_path
  end

  private
    def appointment_params
      params.require(:appointment).permit(:doctor_id, :patient_id, :appointment_date, :appointment_time)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor, notice: 'Doctor Created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor Updated'
    else
      render :edit
    end
  end

def destroy
  @doctor.destroy
  redirect_to :root
end

private
  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path, notie: 'Patient Created'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Patient Updated'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path, notice: 'Patient was deleted'
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/new.html.erb
<h1><h1>Add An Appointment </h1>
<hr />

<%= form_for @appointment do |f| %>
  <%= f.select :doctor_id, options_for_select(@doctors) %>
  <%= f.select :patient_id, options_for_select(@patients) %>

  <%= f.label :appointment_date %>
  <%= f.text_field :appointment_date, required: true, placeholder: 'Appointment Date' %>

  <%= f.label :appointment_time %>
  <%= f.text_field :appointment_time, require: true, placeholder: 'Appointment Time'%>


  <%= f.submit nil, class: 'btn' %>
<% end %>

<hr />
<%= link_to 'All Doctors', doctors_path, class: "btn" %>
<%= link_to 'All Patients', patients_path, class: "btn" %>

app/views/doctors/_form.html.erb
<%= form_for(doctor) do |f| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being save:</h2>

      <ul>
        <%= doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn" %>
    </div>
  <% end %>

app/views/doctors/edit.html.erb
<h1><h1>Edit Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<h1><h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.first_name %></td>
      <td><%= doctor.last_name %></td>
      <td><%= link_to 'Appointments', doctor, class: "btn" %></td>
      <td><%= link_to 'Edit', edit_doctor_path(doctor), class: "btn" %></td>
      <td><%= link_to 'Destroy', doctor, class: "btn", method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br />


<%= link_to 'New Doctor', new_doctor_path, class: "btn" %>
<%= link_to 'Add Appointment to Doctor', new_appointment_path, class: "btn" %>

app/views/doctors/new.html.erb
<h1><h1> New Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/show.html.erb
<% unless @doctor.last_name.empty? %>
  <strong><h1>Dr.<%= @doctor.first_name %><%= @doctor.last_name %></h1>

<hr />
<% end %>

<% if @doctor.patients.any? %>
<h5> Patients </h5>
<ul>
  <% @doctor.appointments.each do |appointments| %>
  <li>
    <% appointments.patient.last_name %> - <%= appointments.appointment_date %>
    <%= link_to 'Remove', appointment_path(appointments), class: "btn", method: :delete, data: {confirm: 'Really delete this?' } %>
  </li>
<% end %>
</ul>
<% else %>
  <h5> No Appointments Found </h5>
<% end %>

<%= link_to 'All Doctors', doctors_path, class: "btn" %>
<%= link_to 'Edit', edit_doctor_path(@doctor), class: "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrOffice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav>

    <div class="nav-wrapper">
      <a href='/' class="brand=logo">DPL Doctors</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <%= link_to 'Doctors', doctors_path %> </li>
        <li> <%= link_to 'Patients', patients_path %> </li>
        <li> <%= link_to 'Add Appointment', new_appointment_path %> </li>
      </ul>
    </div>
  </nav>

  <% flash.each do |key,value| %>
    <div class+"flash <%= key %>"
      <%= value %>
    </div>
  <% end %>

  <div class='container'
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1><h1>Edit Patient</h1>

<%= render 'form', ingredient: @ingredient %>

app/views/patients/index.html.erb
<h1><h1>Patients</h1>

<br />
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
        <td><%= link_to 'Show', patient, class: "btn" %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class: "btn" %></td>
        <td><%= link_to 'Destroy', patient, class: "btn", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class: "btn" %>

app/views/patients/new.html.erb
<<h1><h1>New Patient</h1>

<%= render 'form', ingredient: @patient %>

app/views/patients/show.html.erb
<h1>Patient</h1>

  <h1><%= @patient.first_name %></h1>
  <h1><%= @patient.last_name %></h1>

<% end %>

<% if @patient.appointments.any? %>
<h5> Patients </h5>
<ul>
  <% @patient.appointments.each do |appointments| %>
  <li>
    <% appointments.patient.last_name %> - <%= appointments.appointment_date %>
    <%= link_to 'Remove', appointments_path(appointments), class: "btn", method: :delete %>
  </li>
<% end %>
</ul>
<% else %>
  <h5> No Appointments Found </h5>
<% end %>

<%= link_to 'All Patients', patients_path, class: "btn" %>